In [1]:
import pandas as pd

df = pd.read_csv('traffic.csv')
df.head()

DateTime  Junction  Vehicles           ID
0  2015-11-01 00:00:00         1        15  20151101001
1  2015-11-01 01:00:00         1        13  20151101011
2  2015-11-01 02:00:00         1        10  20151101021
3  2015-11-01 03:00:00         1         7  20151101031
4  2015-11-01 04:00:00         1         9  20151101041

In [2]:
df['DateTime']=pd.to_datetime(df['DateTime'])

df["Year"]=df['DateTime'].dt.year

df["Month"]=df['DateTime'].dt.month

df["Date_no"]=df['DateTime'].dt.day

df["Hour"]=df['DateTime'].dt.hour

df["Day"]= df['DateTime'].dt.strftime("%A")
df

DateTime  Junction  Vehicles           ID  Year  Month   
0     2015-11-01 00:00:00         1        15  20151101001  2015     11  \
1     2015-11-01 01:00:00         1        13  20151101011  2015     11   
2     2015-11-01 02:00:00         1        10  20151101021  2015     11   
3     2015-11-01 03:00:00         1         7  20151101031  2015     11   
4     2015-11-01 04:00:00         1         9  20151101041  2015     11   
...                   ...       ...       ...          ...   ...    ...   
48115 2017-06-30 19:00:00         4        11  20170630194  2017      6   
48116 2017-06-30 20:00:00         4        30  20170630204  2017      6   
48117 2017-06-30 21:00:00         4        16  20170630214  2017      6   
48118 2017-06-30 22:00:00         4        22  20170630224  2017      6   
48119 2017-06-30 23:00:00         4        12  20170630234  2017      6   

       Date_no  Hour     Day  
0            1     0  Sunday  
1            1     1  Sunday  
2            1     2  Sunday  
3            1     3  Sunday  
4            1     4  Sunday  
...        ...   ...     ...  
48115       30    19  Friday  
48116       30    20  Friday  
48117       30    21  Friday  
48118       30    22  Friday  
48119       30    23  Friday  

[48120 rows x 9 columns]

In [3]:
df = df.drop(['DateTime', 'ID'], axis=1)
df.head()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
0         1        15  2015     11        1     0  Sunday
1         1        13  2015     11        1     1  Sunday
2         1        10  2015     11        1     2  Sunday
3         1         7  2015     11        1     3  Sunday
4         1         9  2015     11        1     4  Sunday

In [4]:
df = df[df['Junction']==4]

In [5]:
df.tail()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
48115         4        11  2017      6       30    19  Friday
48116         4        30  2017      6       30    20  Friday
48117         4        16  2017      6       30    21  Friday
48118         4        22  2017      6       30    22  Friday
48119         4        12  2017      6       30    23  Friday

In [6]:
from sklearn.model_selection import train_test_split


In [7]:
# df_train

In [8]:
y = []
for i in range(0,len(df)):
    y.append(df.iloc[i,1])

In [9]:
y

[3,
 1,
 4,
 4,
 2,
 1,
 1,
 4,
 4,
 2,
 2,
 5,
 4,
 6,
 4,
 3,
 6,
 6,
 2,
 3,
 8,
 6,
 4,
 8,
 7,
 5,
 3,
 5,
 2,
 5,
 4,
 3,
 3,
 5,
 10,
 8,
 8,
 6,
 10,
 13,
 14,
 10,
 7,
 10,
 7,
 7,
 17,
 13,
 9,
 5,
 6,
 8,
 4,
 3,
 5,
 3,
 8,
 7,
 10,
 11,
 16,
 13,
 12,
 16,
 11,
 12,
 15,
 15,
 10,
 10,
 11,
 9,
 11,
 6,
 8,
 2,
 2,
 3,
 2,
 2,
 6,
 4,
 8,
 9,
 8,
 11,
 8,
 9,
 11,
 12,
 9,
 7,
 11,
 17,
 14,
 12,
 15,
 12,
 8,
 6,
 1,
 6,
 7,
 3,
 9,
 7,
 14,
 14,
 13,
 15,
 13,
 10,
 11,
 7,
 9,
 12,
 10,
 10,
 11,
 11,
 6,
 6,
 2,
 7,
 7,
 3,
 3,
 2,
 6,
 5,
 8,
 5,
 10,
 15,
 12,
 12,
 13,
 7,
 12,
 9,
 10,
 5,
 13,
 7,
 11,
 4,
 4,
 4,
 3,
 3,
 5,
 5,
 4,
 6,
 7,
 7,
 8,
 8,
 8,
 7,
 5,
 11,
 10,
 14,
 12,
 15,
 11,
 11,
 8,
 8,
 4,
 4,
 2,
 3,
 4,
 3,
 6,
 6,
 4,
 6,
 9,
 9,
 7,
 10,
 9,
 7,
 7,
 8,
 9,
 7,
 9,
 9,
 9,
 6,
 6,
 5,
 7,
 6,
 7,
 4,
 5,
 7,
 12,
 13,
 13,
 9,
 9,
 7,
 13,
 7,
 10,
 7,
 5,
 7,
 10,
 9,
 8,
 8,
 7,
 7,
 3,
 3,
 5,
 5,
 7,
 6,
 8,
 11,
 8,
 10,
 13,
 11,
 1

In [10]:
X_train , X_test, y_train , y_test = train_test_split(df,y, test_size=0.2, random_state=42)


In [11]:
X_train

Junction  Vehicles  Year  Month  Date_no  Hour        Day
45670         4         6  2017      3       20    22     Monday
45554         4         4  2017      3       16     2   Thursday
47347         4        10  2017      5       29    19     Monday
47192         4         6  2017      5       23     8    Tuesday
47155         4         3  2017      5       21    19     Sunday
...         ...       ...   ...    ...      ...   ...        ...
47220         4        10  2017      5       24    12  Wednesday
44242         4         8  2017      1       20    10     Friday
46868         4         7  2017      5        9    20    Tuesday
47548         4         5  2017      6        7     4  Wednesday
44636         4        14  2017      2        5    20     Sunday

[3475 rows x 7 columns]

In [12]:
day_mapping = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}

X_train['Day'] = X_train['Day'].map(day_mapping)
X_test['Day'] = X_test['Day'].map(day_mapping)


In [13]:
X_train = X_train.drop("Vehicles", axis=1)
X_test = X_test.drop("Vehicles", axis=1)


In [14]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import tensorflow
import tensorflow as tf
# from statsmodels.tsa.stattools import adfuller
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras
from keras import callbacks
from tensorflow.keras import layers, Sequential, callbacks
from tensorflow.keras.layers import Conv2D, Flatten, Dense, LSTM, Dropout, GRU, Bidirectional, Conv1D, MaxPooling1D
from tensorflow.keras.optimizers import SGD, Adam
import math
from sklearn.metrics import mean_squared_error
from tensorflow.keras.optimizers.schedules import ExponentialDecay

# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

In [15]:
X_train = np.array(X_train)

In [16]:
X_train[0]

array([   4, 2017,    3,   20,   22,    0], dtype=int64)

In [17]:
X_test= np.array(X_test)

In [18]:
# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [19]:
X_train[0]

array([   4, 2017,    3,   20,   22,    0], dtype=int64)

In [20]:
from sklearn.metrics import mean_absolute_error


model = Sequential()
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))
model.compile(optimizer=Adam(learning_rate=0.1),loss='mean_squared_error')
model.fit(X_train, y_train, epochs=50)
model.predict(X_test)


Epoch 1/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2892.6267
Epoch 2/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 36.4476
Epoch 3/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7381
Epoch 4/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.3717
Epoch 5/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3124
Epoch 6/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12.9887
Epoch 7/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.4847  
Epoch 8/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 11.9025
Epoch 9/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 11.8771
Epoch 10/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - loss: 12.1422
Epoch 11/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.9268
Epoch 12/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 12.2088
Epoch 13/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - loss: 12.6132 
Epoch 14/50
109/109 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - loss: 11.3087
Epoch 15/50
109/109 ━━━━━━

array([[7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],
       [7.4371696],


In [21]:
# len(X_train)

In [22]:
# Pred_MLP = MLP_model(X_train,y_train,X_test, y_test)

In [23]:
def RMSE_Value(test,predicted):
    rmse = math.sqrt(mean_squared_error(test, predicted))
    print("The root mean squared error is {}.".format(rmse))
    return rmse

def MAE_Value(test,predicted):
    mae = mean_absolute_error(test, predicted)
    print("The MAE is {}.".format(mae))
    return mae

#To plot the comparitive plot of targets and predictions
def PredictionsPlot(test,predicted,m):
    plt.figure(figsize=(12,5))
    plt.plot(test, color=colors[m],label="True Value",alpha=0.5 )
    plt.plot(predicted,label="Predicted Values")
    plt.title("Traffic Prediction Vs True values")
    plt.xlabel("DateTime")
    plt.ylabel("Number of Vehicles")
    plt.legend()
    plt.show()

In [24]:
X_train[0]

array([   4, 2017,    3,   20,   22,    0], dtype=int64)

In [25]:
arr = []
arr.append(X_train[0])
val = (model.predict(np.array(arr)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


In [26]:
val[0]

array([7.4371696], dtype=float32)

In [27]:
model_json = model.to_json()
with open("model4.json", "w") as json_file:
    json_file.write(model_json)

# Save model weights
model.save_weights("model_weights4.weights.h5")

In [28]:
from keras.models import model_from_json

# Load model architecture from JSON file
with open("model4.json", "r") as json_file:
    loaded_model_json = json_file.read()
loaded_model = model_from_json(loaded_model_json)

# Load model weights from the saved file
loaded_model.load_weights("model_weights4.weights.h5")

In [29]:

val = (loaded_model.predict(np.array(arr)))
val[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([7.4371696], dtype=float32)