In [44]:
import pandas as pd

df = pd.read_csv('traffic.csv')
df.head()

DateTime  Junction  Vehicles           ID
0  2015-11-01 00:00:00         1        15  20151101001
1  2015-11-01 01:00:00         1        13  20151101011
2  2015-11-01 02:00:00         1        10  20151101021
3  2015-11-01 03:00:00         1         7  20151101031
4  2015-11-01 04:00:00         1         9  20151101041

In [45]:
df['DateTime']=pd.to_datetime(df['DateTime'])

df["Year"]=df['DateTime'].dt.year

df["Month"]=df['DateTime'].dt.month

df["Date_no"]=df['DateTime'].dt.day

df["Hour"]=df['DateTime'].dt.hour

df["Day"]= df['DateTime'].dt.strftime("%A")
df

DateTime  Junction  Vehicles           ID  Year  Month   
0     2015-11-01 00:00:00         1        15  20151101001  2015     11  \
1     2015-11-01 01:00:00         1        13  20151101011  2015     11   
2     2015-11-01 02:00:00         1        10  20151101021  2015     11   
3     2015-11-01 03:00:00         1         7  20151101031  2015     11   
4     2015-11-01 04:00:00         1         9  20151101041  2015     11   
...                   ...       ...       ...          ...   ...    ...   
48115 2017-06-30 19:00:00         4        11  20170630194  2017      6   
48116 2017-06-30 20:00:00         4        30  20170630204  2017      6   
48117 2017-06-30 21:00:00         4        16  20170630214  2017      6   
48118 2017-06-30 22:00:00         4        22  20170630224  2017      6   
48119 2017-06-30 23:00:00         4        12  20170630234  2017      6   

       Date_no  Hour     Day  
0            1     0  Sunday  
1            1     1  Sunday  
2            1     2  Sunday  
3            1     3  Sunday  
4            1     4  Sunday  
...        ...   ...     ...  
48115       30    19  Friday  
48116       30    20  Friday  
48117       30    21  Friday  
48118       30    22  Friday  
48119       30    23  Friday  

[48120 rows x 9 columns]

In [46]:
df = df.drop(['DateTime', 'ID'], axis=1)
df.head()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
0         1        15  2015     11        1     0  Sunday
1         1        13  2015     11        1     1  Sunday
2         1        10  2015     11        1     2  Sunday
3         1         7  2015     11        1     3  Sunday
4         1         9  2015     11        1     4  Sunday

In [47]:
df = df[df['Junction']==3]

In [48]:
df.tail()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
43771         3        33  2017      6       30    19  Friday
43772         3        31  2017      6       30    20  Friday
43773         3        28  2017      6       30    21  Friday
43774         3        26  2017      6       30    22  Friday
43775         3        39  2017      6       30    23  Friday

In [49]:
from sklearn.model_selection import train_test_split


In [50]:
# df_train

In [51]:
y = []
for i in range(0,len(df)):
    y.append(df.iloc[i,1])

In [52]:
y

[9,
 7,
 5,
 1,
 2,
 2,
 3,
 4,
 3,
 6,
 12,
 6,
 6,
 9,
 6,
 6,
 4,
 4,
 6,
 5,
 11,
 8,
 6,
 5,
 5,
 3,
 5,
 5,
 3,
 1,
 5,
 1,
 5,
 8,
 10,
 10,
 11,
 7,
 6,
 9,
 6,
 6,
 8,
 7,
 13,
 15,
 9,
 8,
 10,
 4,
 7,
 5,
 4,
 4,
 3,
 5,
 6,
 6,
 10,
 8,
 10,
 5,
 8,
 8,
 5,
 7,
 4,
 7,
 6,
 6,
 9,
 3,
 2,
 6,
 3,
 6,
 1,
 6,
 2,
 3,
 5,
 5,
 3,
 4,
 7,
 5,
 5,
 7,
 9,
 8,
 7,
 6,
 8,
 5,
 4,
 4,
 6,
 3,
 1,
 2,
 1,
 4,
 4,
 4,
 4,
 5,
 5,
 2,
 7,
 6,
 5,
 4,
 4,
 6,
 8,
 4,
 6,
 5,
 4,
 6,
 3,
 3,
 2,
 3,
 1,
 3,
 2,
 5,
 3,
 7,
 2,
 6,
 5,
 3,
 7,
 3,
 5,
 5,
 8,
 6,
 2,
 5,
 6,
 6,
 3,
 6,
 3,
 4,
 5,
 6,
 1,
 2,
 2,
 2,
 3,
 4,
 4,
 3,
 9,
 3,
 5,
 4,
 4,
 5,
 7,
 3,
 6,
 3,
 4,
 6,
 3,
 3,
 5,
 5,
 2,
 5,
 5,
 6,
 10,
 11,
 3,
 3,
 6,
 4,
 2,
 2,
 7,
 6,
 5,
 6,
 6,
 3,
 3,
 5,
 2,
 6,
 2,
 5,
 5,
 2,
 6,
 7,
 5,
 5,
 6,
 4,
 6,
 3,
 4,
 4,
 6,
 8,
 6,
 5,
 8,
 8,
 12,
 6,
 7,
 4,
 6,
 7,
 3,
 6,
 4,
 6,
 5,
 5,
 2,
 4,
 7,
 6,
 4,
 6,
 2,
 5,
 7,
 9,
 6,
 7,
 6,
 5,
 3,
 5,
 6,
 2,
 4,

In [53]:
X_train , X_test, y_train , y_test = train_test_split(df,y, test_size=0.2, random_state=42)


In [54]:
X_train

Junction  Vehicles  Year  Month  Date_no  Hour        Day
34688         3         6  2016      6       17     8     Friday
30754         3         6  2016      1        5    10    Tuesday
38345         3        19  2016     11       16    17  Wednesday
37521         3        10  2016     10       13     9   Thursday
31711         3         6  2016      2       14     7     Sunday
...         ...       ...   ...    ...      ...   ...        ...
34375         3         4  2016      6        4     7   Saturday
42602         3        10  2017      5       13     2   Saturday
34574         3         6  2016      6       12    14     Sunday
30044         3         5  2015     12        6    20     Sunday
36454         3        18  2016      8       29    22     Monday

[11673 rows x 7 columns]

In [55]:
day_mapping = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}

X_train['Day'] = X_train['Day'].map(day_mapping)
X_test['Day'] = X_test['Day'].map(day_mapping)


In [56]:
X_train = X_train.drop("Vehicles", axis=1)
X_test = X_test.drop("Vehicles", axis=1)


In [57]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import tensorflow
import tensorflow as tf
# from statsmodels.tsa.stattools import adfuller
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras
from keras import callbacks
from tensorflow.keras import layers, Sequential, callbacks
from tensorflow.keras.layers import Conv2D, Flatten, Dense, LSTM, Dropout, GRU, Bidirectional, Conv1D, MaxPooling1D
from tensorflow.keras.optimizers import SGD, Adam
import math
from sklearn.metrics import mean_squared_error
from tensorflow.keras.optimizers.schedules import ExponentialDecay

# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

In [58]:
X_train = np.array(X_train)

In [59]:
X_train[0]

array([   3, 2016,    6,   17,    8,    4], dtype=int64)

In [60]:
X_test= np.array(X_test)

In [61]:
# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [62]:
X_train[0]

array([   3, 2016,    6,   17,    8,    4], dtype=int64)

In [63]:
from sklearn.metrics import mean_absolute_error


model = Sequential()
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))
model.compile(optimizer=Adam(learning_rate=0.1),loss='mean_squared_error')
model.fit(X_train, y_train, epochs=50)
model.predict(X_test)


Epoch 1/50


365/365 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 51112.4258
Epoch 2/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 186.5714
Epoch 3/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 138.6675
Epoch 4/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - loss: 104.2045
Epoch 5/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - loss: 114.2930
Epoch 6/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109.7825
Epoch 7/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 106.5459
Epoch 8/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100.0163
Epoch 9/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 106.0466
Epoch 10/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115.2460
Epoch 11/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 107.2803
Epoch 12/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - loss: 115.0316
Epoch 13/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 103.1965
Epoch 14/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - loss: 100.3414
Epoch 15/50
365/365 ━━━━━━━━

array([[14.052436],
       [14.052436],
       [14.052436],
       ...,
       [14.052436],
       [14.052436],
       [14.052436]], dtype=float32)

In [64]:
# len(X_train)

In [65]:
# Pred_MLP = MLP_model(X_train,y_train,X_test, y_test)

In [66]:
def RMSE_Value(test,predicted):
    rmse = math.sqrt(mean_squared_error(test, predicted))
    print("The root mean squared error is {}.".format(rmse))
    return rmse

def MAE_Value(test,predicted):
    mae = mean_absolute_error(test, predicted)
    print("The MAE is {}.".format(mae))
    return mae

#To plot the comparitive plot of targets and predictions
def PredictionsPlot(test,predicted,m):
    plt.figure(figsize=(12,5))
    plt.plot(test, color=colors[m],label="True Value",alpha=0.5 )
    plt.plot(predicted,label="Predicted Values")
    plt.title("Traffic Prediction Vs True values")
    plt.xlabel("DateTime")
    plt.ylabel("Number of Vehicles")
    plt.legend()
    plt.show()

In [67]:
X_train[0]

array([   3, 2016,    6,   17,    8,    4], dtype=int64)

In [68]:
arr = []
arr.append(X_train[0])
val = (model.predict(np.array(arr)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


In [69]:
val[0]

array([14.052436], dtype=float32)

In [70]:
model_json = model.to_json()
with open("model3.json", "w") as json_file:
    json_file.write(model_json)

# Save model weights
model.save_weights("model_weights3.weights.h5")

In [71]:
from keras.models import model_from_json

# Load model architecture from JSON file
with open("model3.json", "r") as json_file:
    loaded_model_json = json_file.read()
loaded_model = model_from_json(loaded_model_json)

# Load model weights from the saved file
loaded_model.load_weights("model_weights3.weights.h5")

In [72]:

val = (loaded_model.predict(np.array(arr)))
val[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([14.052436], dtype=float32)