In [179]:
import pandas as pd

df = pd.read_csv('traffic.csv')
df.head()

DateTime  Junction  Vehicles           ID
0  2015-11-01 00:00:00         1        15  20151101001
1  2015-11-01 01:00:00         1        13  20151101011
2  2015-11-01 02:00:00         1        10  20151101021
3  2015-11-01 03:00:00         1         7  20151101031
4  2015-11-01 04:00:00         1         9  20151101041

In [180]:
df['DateTime']=pd.to_datetime(df['DateTime'])

df["Year"]=df['DateTime'].dt.year

df["Month"]=df['DateTime'].dt.month

df["Date_no"]=df['DateTime'].dt.day

df["Hour"]=df['DateTime'].dt.hour

df["Day"]= df['DateTime'].dt.strftime("%A")
df

DateTime  Junction  Vehicles           ID  Year  Month   
0     2015-11-01 00:00:00         1        15  20151101001  2015     11  \
1     2015-11-01 01:00:00         1        13  20151101011  2015     11   
2     2015-11-01 02:00:00         1        10  20151101021  2015     11   
3     2015-11-01 03:00:00         1         7  20151101031  2015     11   
4     2015-11-01 04:00:00         1         9  20151101041  2015     11   
...                   ...       ...       ...          ...   ...    ...   
48115 2017-06-30 19:00:00         4        11  20170630194  2017      6   
48116 2017-06-30 20:00:00         4        30  20170630204  2017      6   
48117 2017-06-30 21:00:00         4        16  20170630214  2017      6   
48118 2017-06-30 22:00:00         4        22  20170630224  2017      6   
48119 2017-06-30 23:00:00         4        12  20170630234  2017      6   

       Date_no  Hour     Day  
0            1     0  Sunday  
1            1     1  Sunday  
2            1     2  Sunday  
3            1     3  Sunday  
4            1     4  Sunday  
...        ...   ...     ...  
48115       30    19  Friday  
48116       30    20  Friday  
48117       30    21  Friday  
48118       30    22  Friday  
48119       30    23  Friday  

[48120 rows x 9 columns]

In [181]:
df = df.drop(['DateTime', 'ID'], axis=1)
df.head()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
0         1        15  2015     11        1     0  Sunday
1         1        13  2015     11        1     1  Sunday
2         1        10  2015     11        1     2  Sunday
3         1         7  2015     11        1     3  Sunday
4         1         9  2015     11        1     4  Sunday

In [182]:
df = df[df['Junction']==1]

In [183]:
df.tail()

Junction  Vehicles  Year  Month  Date_no  Hour     Day
14587         1       105  2017      6       30    19  Friday
14588         1        96  2017      6       30    20  Friday
14589         1        90  2017      6       30    21  Friday
14590         1        84  2017      6       30    22  Friday
14591         1        78  2017      6       30    23  Friday

In [184]:
from sklearn.model_selection import train_test_split


In [185]:
df_train

Junction  Vehicles  Year  Month  Date_no  Hour        Day
5504          1        27  2016      6       17     8     Friday
1570          1        27  2016      1        5    10    Tuesday
9161          1        74  2016     11       16    17  Wednesday
8337          1        46  2016     10       13     9   Thursday
2527          1        11  2016      2       14     7     Sunday
...         ...       ...   ...    ...      ...   ...        ...
5191          1        21  2016      6        4     7   Saturday
13418         1        44  2017      5       13     2   Saturday
5390          1        28  2016      6       12    14     Sunday
860           1        21  2015     12        6    20     Sunday
7270          1        59  2016      8       29    22     Monday

[11673 rows x 7 columns]

In [186]:
y = []
for i in range(0,len(df)):
    y.append(df.iloc[i,1])

In [187]:
y

[15,
 13,
 10,
 7,
 9,
 6,
 9,
 8,
 11,
 12,
 15,
 17,
 16,
 15,
 16,
 12,
 12,
 16,
 17,
 20,
 17,
 19,
 20,
 15,
 14,
 12,
 14,
 12,
 12,
 11,
 13,
 14,
 12,
 22,
 32,
 31,
 35,
 26,
 34,
 30,
 27,
 27,
 24,
 26,
 29,
 32,
 30,
 27,
 21,
 18,
 19,
 13,
 11,
 11,
 11,
 14,
 15,
 29,
 33,
 32,
 32,
 29,
 27,
 26,
 28,
 26,
 25,
 29,
 26,
 24,
 25,
 20,
 18,
 18,
 13,
 13,
 10,
 12,
 13,
 11,
 13,
 22,
 26,
 27,
 31,
 24,
 23,
 26,
 26,
 24,
 23,
 25,
 26,
 24,
 26,
 24,
 19,
 20,
 18,
 13,
 13,
 9,
 12,
 12,
 15,
 16,
 23,
 24,
 25,
 24,
 26,
 22,
 20,
 20,
 22,
 26,
 22,
 21,
 21,
 21,
 16,
 18,
 19,
 14,
 12,
 13,
 14,
 14,
 13,
 20,
 22,
 26,
 26,
 21,
 23,
 23,
 19,
 19,
 20,
 24,
 18,
 19,
 16,
 17,
 16,
 16,
 10,
 9,
 8,
 7,
 9,
 8,
 12,
 13,
 17,
 14,
 14,
 14,
 14,
 11,
 15,
 13,
 12,
 17,
 18,
 17,
 16,
 15,
 13,
 16,
 11,
 8,
 10,
 10,
 10,
 9,
 11,
 12,
 18,
 14,
 17,
 14,
 14,
 14,
 12,
 14,
 18,
 13,
 16,
 18,
 14,
 14,
 13,
 15,
 11,
 10,
 9,
 8,
 8,
 10,
 11,
 17,
 19,
 

In [188]:
X_train , X_test, y_train , y_test = train_test_split(X,y, test_size=0.2, random_state=42)


In [189]:
X_train

Junction  Year  Month  Date_no  Hour        Day
5504          1  2016      6       17     8     Friday
1570          1  2016      1        5    10    Tuesday
9161          1  2016     11       16    17  Wednesday
8337          1  2016     10       13     9   Thursday
2527          1  2016      2       14     7     Sunday
...         ...   ...    ...      ...   ...        ...
5191          1  2016      6        4     7   Saturday
13418         1  2017      5       13     2   Saturday
5390          1  2016      6       12    14     Sunday
860           1  2015     12        6    20     Sunday
7270          1  2016      8       29    22     Monday

[11673 rows x 6 columns]

In [190]:
day_mapping = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}

X_train['Day'] = X_train['Day'].map(day_mapping)
X_test['Day'] = X_test['Day'].map(day_mapping)


In [191]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import tensorflow
import tensorflow as tf
# from statsmodels.tsa.stattools import adfuller
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras
from keras import callbacks
from tensorflow.keras import layers, Sequential, callbacks
from tensorflow.keras.layers import Conv2D, Flatten, Dense, LSTM, Dropout, GRU, Bidirectional, Conv1D, MaxPooling1D
from tensorflow.keras.optimizers import SGD, Adam
import math
from sklearn.metrics import mean_squared_error
from tensorflow.keras.optimizers.schedules import ExponentialDecay

# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

In [192]:
X_train = np.array(X_train)

In [193]:
X_train[0]

array([   1, 2016,    6,   17,    8,    4], dtype=int64)

In [194]:
X_test= np.array(X_test)

In [195]:
# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [196]:
X_train[0]

array([   1, 2016,    6,   17,    8,    4], dtype=int64)

In [197]:
from sklearn.metrics import mean_absolute_error


model = Sequential()
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))
model.compile(optimizer=Adam(learning_rate=0.1),loss='mean_squared_error')
model.fit(X_train, y_train, epochs=50)
model.predict(X_test)


Epoch 1/50


365/365 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 27735.7520
Epoch 2/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 831.7842
Epoch 3/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 698.9800
Epoch 4/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 622.2009
Epoch 5/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - loss: 539.3317
Epoch 6/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - loss: 516.1294
Epoch 7/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 549.9526
Epoch 8/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 534.3812
Epoch 9/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - loss: 549.4016
Epoch 10/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - loss: 544.9852
Epoch 11/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 527.4626
Epoch 12/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 530.7094
Epoch 13/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 536.6274
Epoch 14/50
365/365 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 533.6031  
Epoch 15/50
365/365 ━━━━━━━━

array([[45.625324],
       [45.625324],
       [45.625324],
       ...,
       [45.625324],
       [45.625324],
       [45.625324]], dtype=float32)

In [198]:
# len(X_train)

In [199]:
# Pred_MLP = MLP_model(X_train,y_train,X_test, y_test)

In [200]:
def RMSE_Value(test,predicted):
    rmse = math.sqrt(mean_squared_error(test, predicted))
    print("The root mean squared error is {}.".format(rmse))
    return rmse

def MAE_Value(test,predicted):
    mae = mean_absolute_error(test, predicted)
    print("The MAE is {}.".format(mae))
    return mae

#To plot the comparitive plot of targets and predictions
def PredictionsPlot(test,predicted,m):
    plt.figure(figsize=(12,5))
    plt.plot(test, color=colors[m],label="True Value",alpha=0.5 )
    plt.plot(predicted,label="Predicted Values")
    plt.title("Traffic Prediction Vs True values")
    plt.xlabel("DateTime")
    plt.ylabel("Number of Vehicles")
    plt.legend()
    plt.show()

In [201]:
X_train[0]

array([   1, 2016,    6,   17,    8,    4], dtype=int64)

In [202]:
arr = []
arr.append(X_train[0])
val = (model.predict(np.array(arr)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


In [203]:
val[0]

array([45.625324], dtype=float32)

In [204]:
model_json = model.to_json()
with open("model1.json", "w") as json_file:
    json_file.write(model_json)

# Save model weights
model.save_weights("model_weights1.weights.h5")

In [205]:
from keras.models import model_from_json

# Load model architecture from JSON file
with open("model1.json", "r") as json_file:
    loaded_model_json = json_file.read()
loaded_model = model_from_json(loaded_model_json)

# Load model weights from the saved file
loaded_model.load_weights("model_weights1.weights.h5")

In [206]:

val = (loaded_model.predict(np.array(arr)))
val[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([45.625324], dtype=float32)